import "./globals.css";
import { Josefin_Slab } from "next/font/google";
import { CounterProvider } from "./context/provider";

const inter = Josefin_Slab({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="p-2">
          <CounterProvider>{children}</CounterProvider>
        </div>
      </body>
    </html>
  );
}
