import "./globals.css";
import { Josefin_Slab } from "next/font/google";
import { TodosProvider } from "@/context/todos.provider";
import Providers from "@/lib/providers";
import Navbar from "@/components/Navbar";

const inter = Josefin_Slab({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Navbar />
          <TodosProvider>
            <div className="p-2">{children}</div>
          </TodosProvider>
        </Providers>
      </body>
    </html>
  );
}
